TARGET = absolute leafYear passFail grade grade2 passFail posZeroNeg posZeroNeg2 posZeroNeg3 bigLetter bigLetter2 one2Ten one2Tensum multiplyTaple ascii ascii2 star one2TenWhile one2TenDoWhile randomTwoint staticLocalVariable functionSum returnValue power

all : ${TARGET}

absolute : $@
leafYear : $@
passFail : $@
grade : $@
grade2 : $@
passFail : $@
posZeroNeg : $@
posZeroNeg2 : $@
posZeroNeg3 : $@
bigLetter : $@
bigLetter2 : $@
one2Ten : $@
one2Tensum : $@
multiplyTaple : $@
ascii : $@
ascii2 : $@
star : $@
one2TenWhile : $@
one2TenDoWhile : $@
randomTwoint : $@
staticLocalVariable : $@
functionSum : $@
returnValue : $@
power : $@

clean :
	rm ${TARGET}
