TARGET = absolute leafYear passFail grade grade2 passFail posZeroNeg posZeroNeg2 posZeroNeg3 bigLetter bigLetter2 one2Ten one2Tensum
all : ${TARGET}

absolute : $@
leafYear : $@
passFail : $@
grade : $@
grade2 : $@
passFail : $@
posZeroNeg : $@
posZeroNeg2 : $@
posZeroNeg3 : $@
bigLetter : $@
bigLetter2 : $@
one2Ten : $@
one2Tensum : $@

clean :
	rm ${TARGET}
