TARGET = swap selection bubble qsort pointerConcept endian pointer2 functionPointer voidPointer
all : ${TARGET}

swap : $@
selection : $@
bubble : $@
qsort : $@
pointerConcept : $@
endian : $@
pointer2 : $@
functionPointer : $@
voidPointer : $@

clean :
	rm ${TARGET}
