TARGET = swap selection bubble qsort pointerConcept endian pointer2 functionPointer voidPointer arrayPointer arrayAssignement arrayCompare swapFunction sumArrayFunction sumMatrixFunction sumMatrixFunction2 helloStr charPointerOperation strcatExample filePointer fileDescription dynamicAllocation charAdress unionExample enumExample
all : ${TARGET}

swap : $@
selection : $@
bubble : $@
qsort : $@
pointerConcept : $@
endian : $@
pointer2 : $@
functionPointer : $@
voidPointer : $@
arrayPointer : $@
arrayAssignement : $@
arrayCompare : $@
swapFunction : $@
sumArrayFunction : $@
sumMatrixFunction : $@
sumMatrixFunction2 : $@
helloStr : $@
charPointerOperation : $@
strcatExample : $@
filePointer : $@
fileDescription : $@
dynamicAllocation : $@
charAdress : $@
unionExample : $@
enumExample : $@

clean :
	rm ${TARGET}
